#encoding:utf-8
namespace :db do
  task seed: :environment do
    patients
  end
end

def patients
  Patient.delete_all

  @patient1 = Patient.create(
      id: 113932081080001,
      name: '张三丰',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203834',
      gender: '男',
      birthday: '1920-8-17',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248938',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'spfzzz@163.com',
      introduction: '',
      patient_ids: 'A'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient2 = Patient.create(
      id: 113932081080002,
      name: '张无忌',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203831',
      gender: '男',
      birthday: '1920-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248931',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangsanfeng@163.com',
      introduction: '',
      patient_ids: 'B'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor4.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient3 = Patient.create(
      id: 113932081080003,
      name: '因素素',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203832',
      gender: '女',
      birthday: '1925-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248932',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'yinsusu@163.com',
      introduction: '',
      patient_ids: 'C'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor4.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient4 = Patient.create(
      id: 113932081080004,
      name: '高元',
      spell_code: 'LW',
      credential_type: '身份证',
      credential_type_number: '110108197711263179',
      gender: '女',
      birthday: '1977-11-26',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '13381207909',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lishi@163.com',
      introduction: '',
      patient_ids: 'G'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor19.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient5 = Patient.create(
      id: 113932081080005,
      name: '罗卿平',
      spell_code: 'GQ',
      credential_type: '身份证',
      credential_type_number: '220625199211241560',
      gender: '男',
      birthday: '1992-11-24',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15510302177',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'gaoqing@163.com',
      introduction: '',
      patient_ids: 'F'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor6.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient6 = Patient.create(
      id: 113932081080006,
      name: '马志武',
      spell_code: 'ZM',
      credential_type: '身份证',
      credential_type_number: '632221199003082228',
      gender: '男',
      birthday: '1990-03-08',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '18210142581',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangmei@163.com',
      introduction: '',
      patient_ids: 'D2'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor8.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient7 = Patient.create(
      id: 113932081080007,
      name: '郭晋',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826198708011753',
      gender: '男',
      birthday: '1987-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'guoj@163.com',
      introduction: '',
      patient_ids: 'D1'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient8 = Patient.create(
      id: 113932081080008,
      name: '张重阳',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '130826195408011753',
      gender: '男',
      birthday: '1954-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zcy@163.com',
      introduction: '',
      patient_ids: 'Y'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient9 = Patient.create(
      id: 113932081080009,
      name: '黎少平',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197208011753',
      gender: '男',
      birthday: '1972-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lsp@163.com',
      introduction: '',
      patient_ids: 'W'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient10 = Patient.create(
      id: 113932081080010,
      name: '程亚和',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197908011753',
      gender: '男',
      birthday: '1989-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007797',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'cyh@163.com',
      introduction: '',
      patient_ids: 'Q'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient11 = Patient.create(
      id: 113932081080011,
      name: '张轩一',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203834',
      gender: '男',
      birthday: '1920-8-17',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248938',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'spfzzz@163.com',
      introduction: '',
      patient_ids: 'A'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient12 = Patient.create(
      id: 113932081080012,
      name: '张林',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203831',
      gender: '男',
      birthday: '1920-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248931',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangsanfeng@163.com',
      introduction: '',
      patient_ids: 'B'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor4.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient13 = Patient.create(
      id: 113932081080013,
      name: '吕一',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203832',
      gender: '女',
      birthday: '1925-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248932',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'yinsusu@163.com',
      introduction: '',
      patient_ids: 'C'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor4.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient14 = Patient.create(
      id: 113932081080014,
      name: '汪育彤',
      spell_code: 'LW',
      credential_type: '身份证',
      credential_type_number: '110108197711263179',
      gender: '女',
      birthday: '1977-11-26',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '13381207909',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lishi@163.com',
      introduction: '',
      patient_ids: 'G'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor19.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient15 = Patient.create(
      id: 113932081080015,
      name: '周大',
      spell_code: 'GQ',
      credential_type: '身份证',
      credential_type_number: '220625199211241560',
      gender: '男',
      birthday: '1992-11-24',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15510302177',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'gaoqing@163.com',
      introduction: '',
      patient_ids: 'F'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor6.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient16 = Patient.create(
      id: 113932081080016,
      name: '李卓哲',
      spell_code: 'ZM',
      credential_type: '身份证',
      credential_type_number: '632221199003082228',
      gender: '男',
      birthday: '1990-03-08',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '18210142581',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangmei@163.com',
      introduction: '',
      patient_ids: 'D2'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor8.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient17 = Patient.create(
      id: 113932081080017,
      name: '郭风',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826198708011753',
      gender: '男',
      birthday: '1987-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'guoj@163.com',
      introduction: '',
      patient_ids: 'D1'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient18 = Patient.create(
      id: 113932081080018,
      name: '李武宪',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '130826195408011753',
      gender: '男',
      birthday: '1954-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zcy@163.com',
      introduction: '',
      patient_ids: 'Y'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient19 = Patient.create(
      id: 113932081080019,
      name: '汪才顺',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197208011753',
      gender: '男',
      birthday: '1972-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lsp@163.com',
      introduction: '',
      patient_ids: 'W'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient20 = Patient.create(
      id: 113932081080020,
      name: '李长财',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197908011753',
      gender: '男',
      birthday: '1989-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007797',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'cyh@163.com',
      introduction: '',
      patient_ids: 'Q'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient21 = Patient.create(
      id: 113932081080021,
      name: '李泰福',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203834',
      gender: '男',
      birthday: '1920-8-17',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248938',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'spfzzz@163.com',
      introduction: '',
      patient_ids: 'A'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient22 = Patient.create(
      id: 113932081080022,
      name: '李建利',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203831',
      gender: '男',
      birthday: '1920-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248931',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangsanfeng@163.com',
      introduction: '',
      patient_ids: 'B'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient23 = Patient.create(
      id: 113932081080023,
      name: '李泉凤',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203832',
      gender: '女',
      birthday: '1925-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248932',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'yinsusu@163.com',
      introduction: '',
      patient_ids: 'C'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient24 = Patient.create(
      id: 113932081080024,
      name: '于鹏丽',
      spell_code: 'LW',
      credential_type: '身份证',
      credential_type_number: '110108197711263179',
      gender: '女',
      birthday: '1977-11-26',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '13381207909',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lishi@163.com',
      introduction: '',
      patient_ids: 'G'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient25 = Patient.create(
      id: 113932081080025,
      name: '周要为',
      spell_code: 'GQ',
      credential_type: '身份证',
      credential_type_number: '220625199211241560',
      gender: '男',
      birthday: '1992-11-24',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15510302177',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'gaoqing@163.com',
      introduction: '',
      patient_ids: 'F'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient26 = Patient.create(
      id: 113932081080026,
      name: '冯兴国',
      spell_code: 'ZM',
      credential_type: '身份证',
      credential_type_number: '632221199003082228',
      gender: '男',
      birthday: '1990-03-08',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '18210142581',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangmei@163.com',
      introduction: '',
      patient_ids: 'D2'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor8.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient27 = Patient.create(
      id: 113932081080027,
      name: '马建国',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826198708011753',
      gender: '男',
      birthday: '1987-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'guoj@163.com',
      introduction: '',
      patient_ids: 'D1'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient28 = Patient.create(
      id: 113932081080028,
      name: '吕显祖',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '130826195408011753',
      gender: '男',
      birthday: '1954-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zcy@163.com',
      introduction: '',
      patient_ids: 'Y'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient29 = Patient.create(
      id: 113932081080029,
      name: '程孝先',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197208011753',
      gender: '男',
      birthday: '1972-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lsp@163.com',
      introduction: '',
      patient_ids: 'W'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient30 = Patient.create(
      id: 113932081080030,
      name: '甘铁生',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197908011753',
      gender: '男',
      birthday: '1989-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007797',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'cyh@163.com',
      introduction: '',
      patient_ids: 'Q'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient31 = Patient.create(
      id: 113932081080031,
      name: '高大山',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203834',
      gender: '男',
      birthday: '1920-8-17',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248938',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'spfzzz@163.com',
      introduction: '',
      patient_ids: 'A'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient32 = Patient.create(
      id: 113932081080032,
      name: '谢大海',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203831',
      gender: '男',
      birthday: '1920-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248931',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangsanfeng@163.com',
      introduction: '',
      patient_ids: 'B'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor4.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient33 = Patient.create(
      id: 113932081080033,
      name: '马宏宇',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203832',
      gender: '男',
      birthday: '1925-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248932',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'yinsusu@163.com',
      introduction: '',
      patient_ids: 'C'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient34 = Patient.create(
      id: 113932081080034,
      name: '章汉夫',
      spell_code: 'LW',
      credential_type: '身份证',
      credential_type_number: '110108197711263179',
      gender: '男',
      birthday: '1977-11-26',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '13381207909',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lishi@163.com',
      introduction: '',
      patient_ids: 'G'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient35 = Patient.create(
      id: 113932081080035,
      name: '周量',
      spell_code: 'GQ',
      credential_type: '身份证',
      credential_type_number: '220625199211241560',
      gender: '男',
      birthday: '1992-11-24',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15510302177',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'gaoqing@163.com',
      introduction: '',
      patient_ids: 'F'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor6.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient36 = Patient.create(
      id: 113932081080036,
      name: '李佳音',
      spell_code: 'ZM',
      credential_type: '身份证',
      credential_type_number: '632221199003082228',
      gender: '男',
      birthday: '1990-03-08',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '18210142581',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangmei@163.com',
      introduction: '',
      patient_ids: 'D2'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor8.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient37 = Patient.create(
      id: 113932081080037,
      name: '张产',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826198708011753',
      gender: '男',
      birthday: '1987-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'guoj@163.com',
      introduction: '',
      patient_ids: 'D1'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient38 = Patient.create(
      id: 113932081080038,
      name: '李明昌',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '130826195408011753',
      gender: '男',
      birthday: '1954-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zcy@163.com',
      introduction: '',
      patient_ids: 'Y'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient39 = Patient.create(
      id: 113932081080039,
      name: '张吉平',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197208011753',
      gender: '男',
      birthday: '1972-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lsp@163.com',
      introduction: '',
      patient_ids: 'W'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient40 = Patient.create(
      id: 113932081080040,
      name: '张传君',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197908011753',
      gender: '男',
      birthday: '1989-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007797',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'cyh@163.com',
      introduction: '',
      patient_ids: 'Q'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient41 = Patient.create(
      id: 113932081080041,
      name: '张立珍',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203834',
      gender: '女',
      birthday: '1920-8-17',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248938',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'spfzzz@163.com',
      introduction: '',
      patient_ids: 'A'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient42 = Patient.create(
      id: 113932081080042,
      name: '李凤鸣',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203831',
      gender: '男',
      birthday: '1920-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248931',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangsanfeng@163.com',
      introduction: '',
      patient_ids: 'B'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor4.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient43 = Patient.create(
      id: 113932081080043,
      name: '李成果',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '410726198912203832',
      gender: '女',
      birthday: '1925-8-11',
      birthplace: '中国',
      address: '中国武当山',
      nationality: '',
      citizenship: '',
      province: '',
      county: '中国',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201248932',
      home_phone: '',
      home_address: '',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'yinsusu@163.com',
      introduction: '',
      patient_ids: 'C'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient44 = Patient.create(
      id: 113932081080044,
      name: '李晓波',
      spell_code: 'LW',
      credential_type: '身份证',
      credential_type_number: '110108197711263179',
      gender: '男',
      birthday: '1977-11-26',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '13381207909',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lishi@163.com',
      introduction: '',
      patient_ids: 'G'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient45 = Patient.create(
      id: 113932081080045,
      name: '李福安',
      spell_code: 'GQ',
      credential_type: '身份证',
      credential_type_number: '220625199211241560',
      gender: '男',
      birthday: '1992-11-24',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15510302177',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'gaoqing@163.com',
      introduction: '',
      patient_ids: 'F'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor6.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient46 = Patient.create(
      id: 113932081080046,
      name: '黄兴',
      spell_code: 'ZM',
      credential_type: '身份证',
      credential_type_number: '632221199003082228',
      gender: '男',
      birthday: '1990-03-08',
      birthplace: '北京市石景山区',
      address: '北京市石景山区',
      nationality: '汉族',
      citizenship: '中国',
      province: '北京市',
      county: '石景山区',
      photo: '',
      marriage: '未婚',
      mobile_phone: '18210142581',
      home_phone: '',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zhangmei@163.com',
      introduction: '',
      patient_ids: 'D2'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor8.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient47 = Patient.create(
      id: 113932081080047,
      name: '石泰',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826198708011753',
      gender: '男',
      birthday: '1987-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'guoj@163.com',
      introduction: '',
      patient_ids: 'D1'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor3.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient48 = Patient.create(
      id: 113932081080048,
      name: '石玉昆',
      spell_code: '',
      credential_type: '身份证',
      credential_type_number: '130826195408011753',
      gender: '男',
      birthday: '1954-08-01',
      birthplace: '河北',
      address: '河北',
      nationality: '满族',
      citizenship: '中国',
      province: '河北',
      county: '河北某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'zcy@163.com',
      introduction: '',
      patient_ids: 'Y'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

  @patient49 = Patient.create(
      id: 113932081080049,
      name: '史佩平',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197208011753',
      gender: '男',
      birthday: '1972-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007097',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'lsp@163.com',
      introduction: '',
      patient_ids: 'W'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )
  @patient50 = Patient.create(
      id: 113932081080050,
      name: '邱启华',
      spell_code: 'SY',
      credential_type: '身份证',
      credential_type_number: '130826197908011753',
      gender: '男',
      birthday: '1989-08-01',
      birthplace: '山东',
      address: '山东',
      nationality: '满族',
      citizenship: '中国',
      province: '山东',
      county: '山东某县',
      photo: '',
      marriage: '未婚',
      mobile_phone: '15201007797',
      home_phone: '010-123569856',
      home_address: '北京市石景山区5号',
      contact: '',
      contact_phone: '',
      home_postcode: '',
      email: 'cyh@163.com',
      introduction: '',
      patient_ids: 'Q'+Time.new.to_i.to_s,
      education: '',
      household: '',
      doctor_id:@doctor1.id,
      occupation: '',
      orgnization: '',
      orgnization_address: '',
      insurance_type: '',
      insurance_number: ''
  )

end