#encoding:utf-8
namespace :db  do
  task seed:  :environment do
    treatment_relationship
  end
end
def treatment_relationship
  TreatmentRelationship.delete_all
  TreatmentRelationship.create(
      doctor_id:@doctor3.id,
      patient_id:@patient7.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor3.id,
      patient_id:@patient8.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor3.id,
      patient_id:@patient9.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor3.id,
      patient_id:@patient10.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor3.id,
      patient_id:@patient5.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor3.id,
      patient_id:@patient6.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor6.id,
      patient_id:@patient1.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor6.id,
      patient_id:@patient2.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor6.id,
      patient_id:@patient3.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor6.id,
      patient_id:@patient4.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor8.id,
      patient_id:@patient1.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor10.id,
      patient_id:@patient1.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor19.id,
      patient_id:@patient1.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor29.id,
      patient_id:@patient1.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor8.id,
      patient_id:@patient5.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor6.id,
      patient_id:@patient6.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor6.id,
      patient_id:@patient7.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor8.id,
      patient_id:@patient8.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor8.id,
      patient_id:@patient9.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor6.id,
      patient_id:@patient10.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor1.id,
      patient_id:@patient2.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor1.id,
      patient_id:@patient10.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor1.id,
      patient_id:@patient1.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor1.id,
      patient_id:@patient3.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor1.id,
      patient_id:@patient6.id
  )
  TreatmentRelationship.create(
      doctor_id:@doctor1.id,
      patient_id:@patient5.id
  )



end