#encoding:utf-8
namespace :db  do
  task seed:  :environment do
    appointment_schedules_data
  end
end
def appointment_schedules_data
  AppointmentSchedule.delete_all
  AppointmentSchedule.create(
      doctor_id:@doctor3.id,
      dayofweek:2,
      timeblock:13,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor3.id,
      dayofweek:4,
      timeblock:9,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor4.id,
      dayofweek:3,
      timeblock:14,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor4.id,
      dayofweek:6,
      timeblock:8,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor6.id,
      dayofweek:1,
      timeblock:9,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor6.id,
      dayofweek:2,
      timeblock:9,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor6.id,
      dayofweek:5,
      timeblock:10,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor6.id,
      dayofweek:2,
      timeblock:15,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor8.id,
      dayofweek:4,
      timeblock:9,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor8.id,
      dayofweek:2,
      timeblock:11,
      avalailbecount:6
  )
  AppointmentSchedule.create(
      doctor_id:@doctor29.id,
      dayofweek:3,
      timeblock:9,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor1.id,
      dayofweek:2,
      timeblock:10,
      avalailbecount:6
  )
  AppointmentSchedule.create(
      doctor_id:@doctor1.id,
      dayofweek:5,
      timeblock:14,
      avalailbecount:4
  )
  AppointmentSchedule.create(
      doctor_id:@doctor1.id,
      dayofweek:3,
      timeblock:11,
      avalailbecount:6
  )
  AppointmentSchedule.create(
      doctor_id:@doctor6.id,
      dayofweek:3,
      timeblock:16,
      avalailbecount:4
  )
end
