defaults: &defaults
#
#  cis:
#    name: '192.168.1.239'
#    port: '3003'

#  pic0:
#    name: 'pic.greenhealth.mobi'
#    port: '7501'
#  files:
#    name: 'demo.kanbing365.com'
#    port: '7500'
  cis:
    name: 'demo.kanbing365.com'
    port: '9000'
  files:
    name: 'demo.kanbing365.com'
    port: '7500'
  pic:
    name: 'pic.greenhealth.mobi'
    port: '7500'
  pic0:
    name: 'pic.greenhealth.mobi'
    port: '7501'
  files_mount:
    path: '/dfs/'
  video:
    host: 'demo.kanbing365.com'
    player_port: '8082'
    rest_port: '8082'
  Phoebe:
    host: 'demo.kanbing365.com'
    port: '8082'
    dfs: 'services/dfs'
  ct:
    name: '192.168.1.91'
    port: '8080'
#  mimas:
#    name: 192.168.1.119
#    port: 3001
development:
  <<: *defaults

production:

  cis:
    name: demo.kanbing365.com
    port: 9000
  files:
    name: 'demo.kanbing365.com'
    port: '7500'

  pic:
    name: 'pic.greenhealth.mobi'
    port: '7500'

#首页面图片，用于缓存
  pic0:
    name: 'pic.greenhealth.mobi'
    port: '7501'
  files_mount:
    path: '/dfs/'
  video:
    host: 'demo.kanbing365.com'
    player_port: '8082'
    rest_port: '8082'
  #服务接口所在的主机 就是video
  Phoebe:
    host: 'demo.kanbing365.com'
    port: '8082'
    dfs: 'services/dfs'
  ct:
    name: 'demo.kanbing365.com'
    port: '8080'
#  mimas:
#    name:
#    port: