defaults: &defaults
  EMRHost:
    name: 192.168.1.223
    port: 3000
  CISHost:
    name: 192.168.1.239
    port: 3001
  HyperionHost:
      name: 192.168.1.223
      port: 3000
  FilesHost:
      name: files.kanbing365.com
      port: 80
  PICHost:
      name: pic.greenhealth.mobi
      port: 80
#  PACSHost:
#     name: 166.111.131.144
#     port: 8099
#  MimasHost:
#    name:192.168.1.119
#    port:3000



development:
  <<: *defaults

production:
  EMRHost: #和最终配置和启动的端口有关
    name: demo.kanbing365.com
    port: 9001
  CISHost:
    name: demo.kanbing365.com
    port: 9000
  HyperionHost:
    name: demo.kanbing365.com
    port: 80
  FilesHost:
    name: files.kanbing365.com
    port: 80
  PICHost:
     name: pic.greenhealth.mobi
     port: 80
# PACSHost:
#    name: 166.111.131.144
#    port: 8099
#  MimasHost:
#    name:
#    port: