defaults: &defaults

  cis: 'http://192.168.1.239/3003/'

  videoServerIp: 'www.kanbing365.com'

#  pic: 'http://pic.greenhealth.mobi:7500/files/'
  pic: 'http://www.kanbing365.com:7500/files/'
  files: 'http://www.kanbing365.com:7500/files/'
  files_mount: '/dfs/'
  xml_path: '/dfs/xml/'
  Phoebe:
    host: 'demo.kanbing365.com'
    port: '8082'
    dfs: 'services/dfs'

#  jsdicom: 'http://www.kanbing365.com:9002/dicom/show/'
  jsdicom: '/dicom/show/'

  ct: 'http://fitark.org:8080/'

  hospital_code:
    yuquan: '00001'

  #pacs 目录
  pacs_directory: '/pacs'
  #医生页面播放视频ip
  edu_video: 'rtmp://203.195.197.169/vod/'
development:
  <<: *defaults

production:
#  远程会诊视频ip
  videoServerIp: '203.195.197.169'
# pic: 'http://fitark.org:7500/files/'
  pic: 'http://pic.kanbing365.com/files/'
  files: 'http://www.kanbing365.com:7500/files/'
  #files: 'http://fitark.org:7500/files/'
  files_mount: '/dfs/'
  xml_path: '/dfs/xml/'
  Phoebe:
      host: 'www.kanbing365.com'
      port: '8082'
      dfs: 'services/dfs'

#  ct: 'http://fitark.org:8080/'
#  jsdicom: 'http://www.kanbing365.com:9002/dicom/show/'
  jsdicom: '/dicom/show/'
  hospital_code:
    yuquan: '00001'

  pacs_directory: '/pacs'
  #医生页面播放视频ip
  edu_video: 'rtmp://203.195.197.169/vod/'