defaults: &defaults

  cis: 'http://192.168.1.239/3003/'

  videoServerIp: 'www.kanbing365.com'

#  pic: 'http://pic.greenhealth.mobi:7500/files/'
  pic: 'http://fitark.org:7500/files/'
  files: 'http://fitark.org:7500/files/'
  files_mount: '/dfs/'
  xml_path: '/dfs/xml/'
  Phoebe:
    host: 'demo.kanbing365.com'
    port: '8082'
    dfs: 'services/dfs'

#  jsdicom: 'http://www.kanbing365.com:9002/dicom/show/'
  jsdicom: '/dicom/show/'
  #通过settings  获取server机器的ip  video_palyer video_rest 是相同的host port
  # FILESURL 通过 services/dfs  获取 dfs文件服务器内部地址
  video_palyer: 'http://fitark.org:8082/'

  video_rest: 'http://fitark.org:8082/'

  video_ip: 'fitark.org'

  ct: 'http://fitark.org:8080/'

  hospital_code:
    yuquan: '00001'

  #pacs 目录
  pacs_directory: '/pacs'
development:
  <<: *defaults

production:
  videoServerIp: '203.195.197.169'

  pic: 'http://pic.kanbing365.com/files/'

  files: 'http://www.kanbing365.com:7500/files/'
  files_mount: '/dfs/'
  xml_path: '/dfs/xml/'

  #服务接口所在的主机 就是video

  Phoebe:
      host: 'www.kanbing365.com'
      port: '8082'
      dfs: 'services/dfs'
  #通过settings  获取server机器的ip  video_palyer video_rest 是相同的host port
  # FILESURL 通过 services/dfs  获取 dfs文件服务器内部地址
  video_palyer: 'http://fitark.org:8082/'

  video_rest: 'http://fitark.org:8082/'

  video_ip: 'fitark.org'

  ct: 'http://fitark.org:8080/'
#  jsdicom: 'http://www.kanbing365.com:9002/dicom/show/'
  jsdicom: '/dicom/show/'
  hospital_code:
    yuquan: '00001'

  pacs_directory: '/pacs'