defaults: &defaults

  cis:
    name: 192.168.1.239
    port: 3003
#  files:
#    name: 'demo.kanbing365.com'
#    port: '7500'

#  cis:
#    name: demo.kanbing365.com
#    port: 9000
  files:
    name: 'demo.kanbing365.com'
    port: '7500'
  pic:
    name: 'pic.greenhealth.mobi'
    port: '7500'
  files_mount:
    path: '/dfs/'

#  mimas:
#    name: 192.168.1.119
#    port: 3001
development:
  <<: *defaults

production:

  cis:
    name: demo.kanbing365.com
    port: 9000
  files:
    name: 'demo.kanbing365.com'
    port: '7500'

  pic:
    name: 'pic.greenhealth.mobi'
    port: '7500'
  files_mount:
    path: '/dfs/'

#  mimas:
#    name:
#    port: