defaults: &defaults

  cis: 'http://192.168.1.239/3003/'

  videoServerIp: 'www.kanbing365.com'
  mimas: 'http://www.kanbing365.com'
#  pic: 'http://pic.greenhealth.mobi:7500/files/'
  pic: 'http://fitark.org:7500/files/'
#  pic: 'http://www.kanbing365.com:7500/files/'
  files: 'http://www.kanbing365.com:7500/files/'
  files_mount: '/dfs/'
  xml_path: '/dfs/xml/'
  Phoebe:
    host: 'demo.kanbing365.com'
    port: '8082'
    dfs: 'services/dfs'

#  jsdicom: 'http://www.kanbing365.com:9002/dicom/show/'
  jsdicom: '/dicom/show/'

  ct: 'http://fitark.org:8080/'

  hospital_code:
    yuquan: '00001'

  #pacs 目录
  pacs_directory: '/pacs'
  #医生页面播放视频ip
  edu_video: 'rtmp://203.195.197.169/vod/'
  #Settings.weixin.app_id, Settings.weixin.app_secret
  weixin:
    app_id: 'wx814c2d89e8970870'
    app_secret: '751cdb39cb83f3f387d06bde23159897'
    redirect_uri: 'http://166.111.138.125:3000/weixins/login'
    redirect: 'http://166.111.138.125:3000/'
    oauth: 'https://open.weixin.qq.com/connect/oauth2/authorize?'
    sns: 'https://api.weixin.qq.com/sns/oauth2/access_token?'
    access_token: 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&'
    send_message: 'https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token='
    info_uri: 'http://166.111.138.125:3000/weixins/user_info'
    message_uri: 'http://166.111.138.125:3000/weixins/user_message'

  aliyunOSS:
    server: 'oss.aliyuncs.com'
    access_key_id: 'h17xgVZatOgQ6IeJ'
    secret_access_key: '6RrQAXRaurcitBPzdQ18nrvEWjWuWO'
    default_bucket: 'mimas-open'
    video_bucket: 'webadmin-video'
    beijing_server: 'oss-cn-beijing.aliyuncs.com'
    xml_bucket: 'mimas-xml'

  aliyunPacs: 'http://dev-pacs.oss-cn-beijing.aliyuncs.com/'

  yuquan_kanbing365_com:
    hospital_id: 1
    department_id: 1
  kangbing365_gre_medical_org:
    hospital_id: "home"
    department_id: 'home'
development:
  <<: *defaults

production:
#  远程会诊视频ip
  videoServerIp: '203.195.197.169'
  mimas: 'http://www.kanbing365.com'
  #mimas: 'http://fitark.org:9001'
# pic: 'http://fitark.org:7500/files/'
  pic: 'http://pic.kanbing365.com/files/'
  files: 'http://www.kanbing365.com:7500/files/'
  #files: 'http://fitark.org:7500/files/'
  files_mount: '/dfs/'
  xml_path: '/dfs/xml/'
  Phoebe:
      host: 'www.kanbing365.com'
      port: '8082'
      dfs: 'services/dfs'

#  ct: 'http://fitark.org:8080/'
#  jsdicom: 'http://www.kanbing365.com:9002/dicom/show/'
  jsdicom: '/dicom/show/'
  hospital_code:
    yuquan: '00001'

  pacs_directory: '/pacs'
  #医生页面播放视频ip
  edu_video: 'rtmp://203.195.197.169/vod/'
  weixin:
    app_id: 'wx814c2d89e8970870'
    app_secret: '751cdb39cb83f3f387d06bde23159897'
    redirect_uri: 'http://kanbing365.gre-medical.org/weixins/login'
    redirect: 'http://kanbing365.gre-medical.org/'
    oauth: 'https://open.weixin.qq.com/connect/oauth2/authorize?'
    sns: 'https://api.weixin.qq.com/sns/oauth2/access_token?'
    access_token: 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&'
    send_message: 'https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token='
    info_uri: 'http://kanbing365.gre-medical.org/weixins/user_info'
    message_uri: 'http://kanbing365.gre-medical.org/weixins/user_message'
    
  aliyunOSS:
    server: 'oss.aliyuncs.com'
    access_key_id: 'h17xgVZatOgQ6IeJ'
    secret_access_key: '6RrQAXRaurcitBPzdQ18nrvEWjWuWO'
    default_bucket: 'mimas-open'
    default_area: 'hangzhou'
    video_bucket: 'webadmin-video'
    beijing_server: 'oss-cn-beijing.aliyuncs.com'
    xml_bucket: 'mimas-xml'

  aliyunPacs: 'http://dev-pacs.oss-cn-beijing.aliyuncs.com/'


  kangbing365_gre_medical_org:
    hospital_id: 'home'
    department_id: 'home'
  yuquan_kanbing365_com:
    hospital_id: 1
    department_id: 1

